// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Pending>")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "type", Target = "~T:BuildCast.Services.RemotePlayService")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "type", Target = "~T:BuildCast.Services.RemotePlayService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:BuildCast.Services.Navigation.NavigationService.NavigationCommand.ViewModelType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.Navigation.NavigationService.NavigationCommand.LoadViewModel(Windows.UI.Xaml.Controls.Page)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.Navigation.NavigationService.NavigationCommand.GoBackAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.Navigation.IPageWithViewModel`1.UpdateBindings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:BuildCast.Services.IRemoteSystemDescription.Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:BuildCast.Services.IRemoteSystemDescription.Glyph")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.IAvailableSystemsObserver.Removed(BuildCast.Services.IRemoteSystemDescription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.IRemotePlayerService.SubscribeSystemsChange(BuildCast.Services.IAvailableSystemsObserver)~System.IDisposable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.IRemotePlayerService.FindDevices~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.IRemotePlayerService.RemoteActivation(Windows.ApplicationModel.Background.BackgroundTaskDeferral,Windows.ApplicationModel.AppService.AppServiceConnection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:BuildCast.Services.PlayerService.GetSourceForUri~System.Threading.Tasks.Task{System.}")]